version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: project_management
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backspring
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontreact
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
